# docker-compose build
version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./pgdata/pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - ./pgdata/pgadmin-data:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: super-secret
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8081:8080"
    links:
      - "db:pgsql-server"
    depends_on:
      db:
        condition: service_healthy